### ISSUE TITLE
1.1.2 stopped working

### ISSUE THREAD

**Issue by pyalxx** [faye/faye#416]
Hi,

Faye 1.0.3 worked normally in my project, but after update to 1.1.2 it stopped working - I don't receive any notifications on client.

Here is my setup:

faye.ru
```ruby
require 'faye'
begin
  require 'logger'

  logger = Logger.new(STDOUT)
  logger.level = Logger::INFO
  Faye.logger = logger
end

bayeux = Faye::RackAdapter.new(:mount => '/faye', :timeout => 25)

run bayeux
```
I'm running it with
```bash
bundle exec rackup -s puma faye.ru -P pids/faye.pid -E production
```
Server starts normally and logs to console

Now I'm trying to publish event to client from rails console (rails c) with basic example
```ruby
EM.run {
  client = Faye::Client.new('http://localhost:9292/faye')
  client.publish('/users/2/update', {test: 'test'}.to_json)
}
```
I'm getting following error
```
NoMethodError: undefined method `[]' for nil:NilClass
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/faye-1.1.2/lib/faye/transport/web_socket.rb:75:in `block in connect'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/faye-websocket-0.10.1/lib/faye/websocket/api/event_target.rb:44:in `call'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/faye-websocket-0.10.1/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/faye-websocket-0.10.1/lib/faye/websocket/api.rb:99:in `open'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/faye-websocket-0.10.1/lib/faye/websocket/api.rb:39:in `block in initialize'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `call'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `each'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `emit'
        from /Users/oleksiipysanko/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver.rb:131:in `open'
...
```
Please, let me know, maybe I'm missing something. 

The strange thing is that for some reason events are no more published from ruby, but clients connect normally - I see new subscriptions in faye output.

Thanks!

**Comment by pyalxx** [comment]
Ok, it was related to https://github.com/faye/faye-websocket-ruby/issues/82

Adding

```ruby
gem 'faye-websocket', git: 'https://github.com/faye/faye-websocket-ruby.git'
```

to Gemfile resolves the issue

**Comment by jcoglan** [comment]
Sorry about this, it will be fixed in faye-websocket 0.10.2. Hopefully I can get that released within the next week.
