### ISSUE TITLE
React native faye client subscription not working 

### ISSUE THREAD

**Issue by SubhaPrince** [faye/faye#478]
We are using faye server in Rails project with secret token and that is working fine. But now we are moving it to our clients to **react native**. The react native clients are not receiving any messages on subscription to a specific channel, I am suspecting this is happing react native client not passing any secret token. can some body help example where we can pass the secret token along with the react native faye client. Below is my sample code..
 

import Faye from "faye";
var faye_url = "http://xxx.com:9292/faye";
var fayeClient = new Faye.Client(faye_url);
var channel = "/conversations/xxxx";
class FayeClient {
  componentWillMount() {}
  constructor() {
    this.msg = fayeClient.subscribe(channel, function(message) {
     // I am expecting below alert to fire when ever there is a new message in a given 
    // channel but here nothing happens
      alert("message obtained");
    });  
  }
}

**Comment by jcoglan** [comment]
Have you checked that the client works with a basic Faye server, not running any authentication extensions or other extensions? Is the client sending requests? Is the client getting responses from the server saying it's not authorised, or is it not getting responses at all? Have you tried turning on logging to see what's being sent/received?

**Comment by SubhaPrince** [comment]
@jcoglan  thanks for your response. I am a beginner of react native. Do you have any proper example for implementation of  faye with react native?

**Comment by jcoglan** [comment]
Unfortunately I don't have any experience with it either, but you could try asking people who commented on #431, which is what prompted us to add React Native support.

**Comment by jcoglan** [comment]
Though having said that if the server is crashing that sounds like a bug in the server. If you're able to paste a `curl` command here that reproduced the request that crashes the server, I'll look into it.

**Comment by SubhaPrince** [comment]
**Here is a command**
curl http://localhost:9292/faye -d 'message={"channel":"message/8237", "data":"hello", "ext":{"private_pub_token":"mykey"}}'

**Outut**
[{"channel":"/message/8237","successful":true}

Invalid token in react native log  when i am debugging. But same token is working to my rails existing project.

**Comment by jcoglan** [comment]
I've tried the message you gave, but it does not crash the server. However, the server does say that the channel `message/8237` is invalid, because it does not have a leading slash; it should be `/message/8237`.

**Comment by SubhaPrince** [comment]
that is typo :). I think there is something which i am messing bcoz if i type  this.msg._client._state returns "**3**" means connected. but the scope of subscription is not invoking. I am not getting any proper documentation where i can implement this thing. faye teams also not sharing of implementation for react native.

**Comment by jcoglan** [comment]
> but the scope of subscription is not invoking

I'm sorry, I'm not sure what you mean by "the scope is not invoking" here. Could you try to explain what you're seeing in more detail?

> I am not getting any proper documentation where i can implement this thing. faye teams also not sharing of implementation for react native.

As I said, I don't have any experience with React Native; all I know is that we adjusted how the long-polling transport works in 1.2.0 so that it could work in the React Native environment.

You know that the client is performing a handshake successfully (hence `_state = 3`), so it must be a problem with either `/meta/subscribe` calls that register subscriptions, or `/meta/connect` which polls for messages. Have you inspected the logs for these messages? (Set `Faye.logger = console`.) Can you see how the server is responding to them, that might give you a hint about why you're not receiving messages.

**Comment by SubhaPrince** [comment]
**How can i call a object method inside the subcribe method** 
this.test is not a function getting **error** when i am calling this way

fayeClient.subscribe(channel, function(message) {
      this.test()
});

test(){
 alert("abc")
}

**Comment by jcoglan** [comment]
Could you include more of your code, for example the complete class you're working on? The code you've pasted is a syntax error as-is because the `test` definition cannot appear in statement position. I'm assuming these are snippets from a larger bit of code.

**Comment by touseefmurtaza-nxb** [comment]
can we use faye on react native client side?
because for me it showing "Uncaught ReferenceError: Faye is not defined"
even after installing faye through "npm install faye --save" and import faye in my App.js file
import Faye from 'faye';

**Comment by jcoglan** [comment]
You should be able to use it, as far as I know, although as I said we don't have specific experience with React Native and don't test specifically for it. `import faye from 'faye'` should give you the client-side library, if you're building with webpack.

Is this an ongoing issue, or can I close it?

**Comment by jcoglan** [comment]
As this issue has not been replied to in a long time, I am going to close it, but please do re-open if you have further information :)
